spring.profiles.active=dev
spring.application.name=payment
# MERCADOPAGO_ACCESS_TOKEN=APP_USR-seu-token-real-aqui

# Isso lerá a variável do Docker ou usará MOCK_TOKEN se o Spring não achar nada
mercadopago.access.token=${MERCADOPAGO_ACCESS_TOKEN:MOCK_TOKEN}

# Configurações do Banco (Garanta que combinem com o Docker)
spring.datasource.url=jdbc:mysql://mysql:3306/mydatabase?createDatabaseIfNotExist=true
spring.datasource.username=myuser
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Força a criação das tabelas do Spring Session no MySQL
spring.session.jdbc.initialize-schema=always
spring.session.store-type=jdbc

resilience4j.retry.instances.mercadopago.max-attempts=3
resilience4j.retry.instances.mercadopago.wait-duration=2s
resilience4j.retry.instances.mercadopago.retry-exceptions=org.springframework.web.client.HttpServerErrorException